//
// UntitledView.h
// Generated by Core Animator version 1.0 on 15/12/4.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface UntitledView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// open
- (void)addOpenAnimation;
- (void)addOpenAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addOpenAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addOpenAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addOpenAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeOpenAnimation;

- (void)removeAllAnimations;

@end